/** Fixed schema-5 fixtures. Never rebuild these from mutable defaults. */
export const INITIAL_SETTINGS_DOCUMENT_V5_TEXT = "{\"connections\":{\"builtin:dry-run\":{\"auth\":{\"type\":\"none\"},\"baseUrl\":null,\"headers\":[],\"name\":\"Dry Run\",\"preset\":\"dry-run\",\"protocol\":\"dry-run\",\"timeouts\":{\"firstTokenMs\":1000,\"idleMs\":1000,\"responseHeaderMs\":1000,\"totalMs\":5000}}},\"models\":{\"builtin:dry-run\":{\"capabilities\":{\"assistantPrefill\":\"unsupported\",\"imageInput\":\"unsupported\",\"promptCaching\":\"unsupported\",\"reasoningEffort\":\"unsupported\",\"temperature\":\"supported\"},\"connectionId\":\"builtin:dry-run\",\"discovered\":{\"contextWindow\":32768},\"name\":\"Dry Run\",\"overrides\":{},\"remoteId\":\"dry-run\"}},\"profiles\":{\"default\":{\"cachePolicy\":\"off\",\"generationReasoning\":{\"effort\":\"default\",\"kind\":\"independent\",\"thinkingMode\":\"default\"},\"maxOutputTokens\":2048,\"modelId\":\"builtin:dry-run\",\"name\":\"Default\",\"temperature\":0.8}},\"routing\":{\"default\":\"default\"},\"schemaVersion\":5,\"writing\":{\"asideGuidance\":\"\",\"defaultAuthorBrief\":\"Continue the story in its established voice.\",\"defaultContinueDirection\":\"Continue the story.\",\"rewriteGuidance\":\"\",\"summaryGuidance\":\"\",\"titleGuidance\":\"\"}}";

export const INITIAL_SETTINGS_STATE_V5_TEXT = "{\"activation\":null,\"activeRevision\":1,\"documents\":{\"1\":{\"connections\":{\"builtin:dry-run\":{\"auth\":{\"type\":\"none\"},\"baseUrl\":null,\"headers\":[],\"name\":\"Dry Run\",\"preset\":\"dry-run\",\"protocol\":\"dry-run\",\"timeouts\":{\"firstTokenMs\":1000,\"idleMs\":1000,\"responseHeaderMs\":1000,\"totalMs\":5000}}},\"models\":{\"builtin:dry-run\":{\"capabilities\":{\"assistantPrefill\":\"unsupported\",\"imageInput\":\"unsupported\",\"promptCaching\":\"unsupported\",\"reasoningEffort\":\"unsupported\",\"temperature\":\"supported\"},\"connectionId\":\"builtin:dry-run\",\"discovered\":{\"contextWindow\":32768},\"name\":\"Dry Run\",\"overrides\":{},\"remoteId\":\"dry-run\"}},\"profiles\":{\"default\":{\"cachePolicy\":\"off\",\"generationReasoning\":{\"effort\":\"default\",\"kind\":\"independent\",\"thinkingMode\":\"default\"},\"maxOutputTokens\":2048,\"modelId\":\"builtin:dry-run\",\"name\":\"Default\",\"temperature\":0.8}},\"routing\":{\"default\":\"default\"},\"schemaVersion\":5,\"writing\":{\"asideGuidance\":\"\",\"defaultAuthorBrief\":\"Continue the story in its established voice.\",\"defaultContinueDirection\":\"Continue the story.\",\"rewriteGuidance\":\"\",\"summaryGuidance\":\"\",\"titleGuidance\":\"\"}}},\"lastActivationOutcome\":null,\"lastTransaction\":null,\"pendingRevision\":null,\"previousRevision\":null,\"schemaVersion\":5,\"settingsRevisionClock\":1,\"stateGeneration\":1}";

export const INITIAL_SETTINGS_DOCUMENT_V5_HASH =
  "9b3fc618e258483b6fb0fe1dc50dd6ab4e7da8b541010194c7fd089d03183413" as const;
export const INITIAL_SETTINGS_STATE_V5_HASH =
  "e9f6bff772d3e624daf61248ef152b3df14cc9e7d08d6facb1b3063196f200cf" as const;
export const INITIAL_SETTINGS_DOCUMENT_V5_SHA256 =
  "fb3d17454bedbc96b9b3218eaf631f2744b596353ca2dd4026601c1d956a51bb" as const;
export const INITIAL_SETTINGS_STATE_V5_SHA256 =
  "f9f0776d37519dd20d546c1c77a3cc30c189c2a02210b4c4db0191941d8f3b85" as const;
