/** Fixed predecessor fixtures. The predecessor never writes these bytes. */
export const INITIAL_SETTINGS_DOCUMENT_V4_TEXT = "{\"connections\":{\"builtin:dry-run\":{\"auth\":{\"type\":\"none\"},\"baseUrl\":null,\"headers\":[],\"name\":\"Dry Run\",\"preset\":\"dry-run\",\"protocol\":\"dry-run\",\"timeouts\":{\"firstTokenMs\":1000,\"idleMs\":1000,\"responseHeaderMs\":1000,\"totalMs\":5000}}},\"models\":{\"builtin:dry-run\":{\"capabilities\":{\"assistantPrefill\":\"unsupported\",\"imageInput\":\"unsupported\",\"promptCaching\":\"unsupported\",\"reasoningEffort\":\"unsupported\",\"temperature\":\"supported\"},\"connectionId\":\"builtin:dry-run\",\"discovered\":{\"contextWindow\":32768},\"name\":\"Dry Run\",\"overrides\":{},\"remoteId\":\"dry-run\"}},\"profiles\":{\"default\":{\"cachePolicy\":\"off\",\"effort\":\"default\",\"maxOutputTokens\":2048,\"modelId\":\"builtin:dry-run\",\"name\":\"Default\",\"temperature\":0.8,\"thinkingMode\":\"default\"}},\"routing\":{\"default\":\"default\"},\"schemaVersion\":4,\"writing\":{\"defaultAuthorBrief\":\"Continue the story in its established voice.\"}}";

export const INITIAL_SETTINGS_STATE_V4_TEXT = "{\"activation\":null,\"activeRevision\":1,\"documents\":{\"1\":{\"connections\":{\"builtin:dry-run\":{\"auth\":{\"type\":\"none\"},\"baseUrl\":null,\"headers\":[],\"name\":\"Dry Run\",\"preset\":\"dry-run\",\"protocol\":\"dry-run\",\"timeouts\":{\"firstTokenMs\":1000,\"idleMs\":1000,\"responseHeaderMs\":1000,\"totalMs\":5000}}},\"models\":{\"builtin:dry-run\":{\"capabilities\":{\"assistantPrefill\":\"unsupported\",\"imageInput\":\"unsupported\",\"promptCaching\":\"unsupported\",\"reasoningEffort\":\"unsupported\",\"temperature\":\"supported\"},\"connectionId\":\"builtin:dry-run\",\"discovered\":{\"contextWindow\":32768},\"name\":\"Dry Run\",\"overrides\":{},\"remoteId\":\"dry-run\"}},\"profiles\":{\"default\":{\"cachePolicy\":\"off\",\"effort\":\"default\",\"maxOutputTokens\":2048,\"modelId\":\"builtin:dry-run\",\"name\":\"Default\",\"temperature\":0.8,\"thinkingMode\":\"default\"}},\"routing\":{\"default\":\"default\"},\"schemaVersion\":4,\"writing\":{\"defaultAuthorBrief\":\"Continue the story in its established voice.\"}}},\"lastActivationOutcome\":null,\"lastTransaction\":null,\"pendingRevision\":null,\"previousRevision\":null,\"schemaVersion\":4,\"settingsRevisionClock\":1,\"stateGeneration\":1}";

export const INITIAL_SETTINGS_DOCUMENT_V4_HASH =
  "6cd180f84128c9d9d249957cdf0591ac8bd26396baf2bb61981f84876c759fab" as const;
export const INITIAL_SETTINGS_STATE_V4_HASH =
  "55f1b074ee9d2f9d71ea2c6e92744a43c2b906c4b0dcb4135284fe8110055816" as const;
export const INITIAL_SETTINGS_DOCUMENT_V4_SHA256 =
  "f5c3e1b07f199caf688990f7141cfcec1bcba6d8d72619fb7309363d01fe1afe" as const;
export const INITIAL_SETTINGS_STATE_V4_SHA256 =
  "6f8ebdf0b82d95dd35f1181339c28eecc010ee58b6a1a3cf1b090851bc6d147c" as const;
