/**
 * Package facts for the pinned Pi subscription adapter.
 *
 * `@earendil-works/pi-ai` declares a broad provider set. The release imports
 * only its Anthropic and OpenAI Codex providers plus its Bun OAuth registry.
 * A Bun 1.4.0 metafile for that exact entry graph contains the four packages
 * below. Other Pi provider packages do not contribute modules to the compiled
 * executable.
 */
export const PI_AI_BUNDLED_PACKAGE_NAMES = Object.freeze([
  "@anthropic-ai/sdk",
  "@earendil-works/pi-ai",
  "partial-json",
  "typebox"
] as const);

/** Packages installed for Pi providers that the standalone does not import. */
export const PI_AI_TREE_SHAKEN_PACKAGE_NAMES = Object.freeze([
  "@aws-crypto/sha256-browser",
  "@aws-crypto/sha256-js",
  "@aws-crypto/supports-web-crypto",
  "@aws-crypto/util",
  "@aws-sdk/client-bedrock-runtime",
  "@aws-sdk/core",
  "@aws-sdk/credential-provider-env",
  "@aws-sdk/credential-provider-http",
  "@aws-sdk/credential-provider-ini",
  "@aws-sdk/credential-provider-login",
  "@aws-sdk/credential-provider-node",
  "@aws-sdk/credential-provider-process",
  "@aws-sdk/credential-provider-sso",
  "@aws-sdk/credential-provider-web-identity",
  "@aws-sdk/eventstream-handler-node",
  "@aws-sdk/middleware-eventstream",
  "@aws-sdk/middleware-websocket",
  "@aws-sdk/nested-clients",
  "@aws-sdk/signature-v4-multi-region",
  "@aws-sdk/token-providers",
  "@aws-sdk/types",
  "@aws-sdk/util-locate-window",
  "@aws-sdk/xml-builder",
  "@aws/lambda-invoke-store",
  "@babel/runtime",
  "@earendil-works/pi-telemetry",
  "@google/genai",
  "@opentelemetry/api",
  "@protobufjs/aspromise",
  "@protobufjs/base64",
  "@protobufjs/codegen",
  "@protobufjs/eventemitter",
  "@protobufjs/fetch",
  "@protobufjs/float",
  "@protobufjs/path",
  "@protobufjs/pool",
  "@protobufjs/utf8",
  "@smithy/core",
  "@smithy/credential-provider-imds",
  "@smithy/fetch-http-handler",
  "@smithy/is-array-buffer",
  "@smithy/node-http-handler",
  "@smithy/signature-v4",
  "@smithy/types",
  "@smithy/util-buffer-from",
  "@smithy/util-utf8",
  "@types/node",
  "@types/retry",
  "agent-base",
  "base64-js",
  "bignumber.js",
  "bowser",
  "buffer-equal-constant-time",
  "data-uri-to-buffer",
  "debug",
  "ecdsa-sig-formatter",
  "extend",
  "fetch-blob",
  "formdata-polyfill",
  "gaxios",
  "gcp-metadata",
  "google-auth-library",
  "google-logging-utils",
  "http-proxy-agent",
  "https-proxy-agent",
  "json-bigint",
  "json-schema-to-ts",
  "jwa",
  "jws",
  "long",
  "ms",
  "node-domexception",
  "node-fetch",
  "openai",
  "p-retry",
  "protobufjs",
  "retry",
  "safe-buffer",
  "ts-algebra",
  "tslib",
  "undici-types",
  "web-streams-polyfill",
  "ws"
] as const);
