import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { isSemVer } from "../shared/semver.js";

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const CHANGELOG_FILE = path.join(ROOT, "CHANGELOG.md");
const OUTPUT_FILE = path.join(ROOT, "shared", "release-notes.ts");

export interface ParsedReleaseNote {
  readonly version: string;
  readonly date: string;
  readonly body: string;
}

// A release heading reads "<semver> - <YYYY-MM-DD>". A prerelease version
// such as "0.6.0-rc.1" has no space around its own hyphen, so the single
// " - " separator below stays unambiguous.
const RELEASE_HEADING = /^(.+) - (\d{4}-\d{2}-\d{2})$/;

/**
 * Parse every released section of `CHANGELOG.md`. A `## Unreleased` section
 * is not a release, and is skipped. Every other `## ` heading must read as
 * `<semver> - <YYYY-MM-DD>`, or the changelog is malformed: this throws
 * rather than silently dropping the section, so a bad heading fails the
 * build instead of shipping a binary with a gap in its own history.
 *
 * Sections are returned in file order, which is newest first.
 */
export function parseReleaseNotes(changelog: string): ParsedReleaseNote[] {
  const lines = changelog.split("\n");
  const headingLines: number[] = [];
  for (let index = 0; index < lines.length; index += 1) {
    if (lines[index]!.startsWith("## ")) headingLines.push(index);
  }
  const notes: ParsedReleaseNote[] = [];
  for (let cursor = 0; cursor < headingLines.length; cursor += 1) {
    const lineIndex = headingLines[cursor]!;
    const title = lines[lineIndex]!.slice(3).trim();
    const bodyStart = lineIndex + 1;
    const bodyEnd = cursor + 1 < headingLines.length ? headingLines[cursor + 1]! : lines.length;
    if (title === "Unreleased") continue;
    const match = RELEASE_HEADING.exec(title);
    if (match === null || !isSemVer(match[1]!)) {
      throw new Error(
        `CHANGELOG.md line ${lineIndex + 1} has a release heading 1667 cannot parse: `
        + `"## ${title}". A release heading must read "## <semver> - <YYYY-MM-DD>", `
        + `for example "## 0.2.1 - 2026-08-01".`
      );
    }
    const body = trimBlankLines(lines.slice(bodyStart, bodyEnd)).join("\n");
    notes.push({ version: match[1]!, date: match[2]!, body });
  }
  return notes;
}

function trimBlankLines(lines: string[]): string[] {
  let start = 0;
  let end = lines.length;
  while (start < end && lines[start]!.trim().length === 0) start += 1;
  while (end > start && lines[end - 1]!.trim().length === 0) end -= 1;
  return lines.slice(start, end);
}

function generatedSource(notes: ParsedReleaseNote[]): string {
  const entries = notes.map((note) => [
    "  {",
    `    version: ${JSON.stringify(note.version)},`,
    `    date: ${JSON.stringify(note.date)},`,
    `    body: ${JSON.stringify(note.body)}`,
    "  }"
  ].join("\n"));
  const list = entries.length === 0 ? "[]" : `[\n${entries.join(",\n")}\n]`;
  return [
    "// GENERATED FILE. Source: CHANGELOG.md.",
    "// Run `npm run notes:write` to regenerate. Do not edit this file by hand.",
    "",
    "export interface ReleaseNote {",
    "  readonly version: string;",
    "  readonly date: string;",
    "  readonly body: string;",
    "}",
    "",
    "/** Every released CHANGELOG.md section, newest first. `Unreleased` is not",
    " *  a release, and is not included. */",
    `export const RELEASE_NOTES: readonly ReleaseNote[] = ${list};`,
    ""
  ].join("\n");
}

async function assertExact(file: string, expected: string): Promise<void> {
  let actual: string;
  try {
    actual = await readFile(file, "utf8");
  } catch (error) {
    throw new Error(`Generated release notes artifact is missing: ${path.relative(ROOT, file)}; run npm run notes:write`, { cause: error });
  }
  if (actual !== expected) {
    throw new Error(`Generated release notes artifact is stale: ${path.relative(ROOT, file)}; run npm run notes:write`);
  }
}

const mode = process.argv[2];
if (mode === "--write") {
  const changelog = await readFile(CHANGELOG_FILE, "utf8");
  const notes = parseReleaseNotes(changelog);
  await writeFile(OUTPUT_FILE, generatedSource(notes));
} else if (mode === "--check") {
  const changelog = await readFile(CHANGELOG_FILE, "utf8");
  const notes = parseReleaseNotes(changelog);
  await assertExact(OUTPUT_FILE, generatedSource(notes));
} else {
  throw new Error("Usage: tsx scripts/release-notes.ts --write|--check");
}
